"""Type stubs for phonenumbers package."""

from typing import Generator, List, Optional, Union, Iterator
from typing_extensions import Self

__version__: str

class NumberParseException(Exception):
    INVALID_COUNTRY_CODE: int
    NOT_A_NUMBER: int
    TOO_SHORT_AFTER_IDD: int
    TOO_SHORT_NSN: int
    TOO_LONG: int
    
    def __init__(self, error_type: int, msg: str) -> None: ...

class PhoneNumberFormat:
    E164: int
    INTERNATIONAL: int
    NATIONAL: int
    RFC3966: int
    
    @classmethod
    def to_string(cls, format_type: int) -> str: ...

class PhoneNumberType:
    FIXED_LINE: int
    MOBILE: int
    FIXED_LINE_OR_MOBILE: int
    TOLL_FREE: int
    PREMIUM_RATE: int
    SHARED_COST: int
    VOIP: int
    PERSONAL_NUMBER: int
    PAGER: int
    UAN: int
    VOICEMAIL: int
    UNKNOWN: int
    
    @classmethod
    def to_string(cls, number_type: int) -> str: ...

class CountryCodeSource:
    UNSPECIFIED: int
    FROM_NUMBER_WITH_PLUS_SIGN: int
    FROM_NUMBER_WITH_IDD: int
    FROM_NUMBER_WITHOUT_PLUS_SIGN: int
    FROM_DEFAULT_COUNTRY: int
    
    @classmethod
    def to_string(cls, source_type: int) -> str: ...

class ValidationResult:
    IS_POSSIBLE: int
    IS_POSSIBLE_LOCAL_ONLY: int
    INVALID_COUNTRY_CODE: int
    TOO_SHORT: int
    INVALID_LENGTH: int
    TOO_LONG: int
    
    @classmethod
    def to_string(cls, result_type: int) -> str: ...

class MatchType:
    INVALID_NUMBER: int
    NOT_A_NUMBER: int
    NO_MATCH: int
    SHORT_NSN_MATCH: int
    NSN_MATCH: int
    EXACT_MATCH: int
    
    @classmethod
    def to_string(cls, match_type: int) -> str: ...

class Leniency:
    POSSIBLE: int
    VALID: int
    STRICT_GROUPING: int
    EXACT_GROUPING: int
    
    @classmethod
    def to_string(cls, leniency_type: int) -> str: ...

class PhoneNumber:
    def __init__(
        self,
        country_code: Optional[int] = None,
        national_number: Optional[int] = None,
        extension: Optional[str] = None,
        italian_leading_zero: Optional[bool] = None,
        number_of_leading_zeros: Optional[int] = None,
        raw_input: Optional[str] = None,
        country_code_source: Optional[int] = None,
        preferred_domestic_carrier_code: Optional[str] = None,
    ) -> None: ...
    
    @property
    def country_code(self) -> int: ...
    @country_code.setter
    def country_code(self, value: int) -> None: ...
    
    @property
    def national_number(self) -> int: ...
    @national_number.setter
    def national_number(self, value: int) -> None: ...
    
    @property
    def extension(self) -> Optional[str]: ...
    @extension.setter
    def extension(self, value: Optional[str]) -> None: ...
    
    @property
    def italian_leading_zero(self) -> bool: ...
    @italian_leading_zero.setter
    def italian_leading_zero(self, value: bool) -> None: ...
    
    @property
    def number_of_leading_zeros(self) -> int: ...
    @number_of_leading_zeros.setter
    def number_of_leading_zeros(self, value: int) -> None: ...
    
    @property
    def raw_input(self) -> Optional[str]: ...
    @raw_input.setter
    def raw_input(self, value: Optional[str]) -> None: ...
    
    @property
    def country_code_source(self) -> int: ...
    @country_code_source.setter
    def country_code_source(self, value: int) -> None: ...
    
    @property
    def preferred_domestic_carrier_code(self) -> Optional[str]: ...
    @preferred_domestic_carrier_code.setter
    def preferred_domestic_carrier_code(self, value: Optional[str]) -> None: ...
    
    def merge_from(self, other: PhoneNumber) -> None: ...

class FrozenPhoneNumber:
    def __init__(
        self,
        phone_number_or_country_code: Optional[Union[PhoneNumber, int]] = None,
        national_number: Optional[int] = None,
        extension: Optional[str] = None,
        italian_leading_zero: Optional[bool] = None,
        number_of_leading_zeros: Optional[int] = None,
        raw_input: Optional[str] = None,
        country_code_source: Optional[int] = None,
        preferred_domestic_carrier_code: Optional[str] = None,
    ) -> None: ...
    
    @property
    def country_code(self) -> int: ...
    @property
    def national_number(self) -> int: ...
    @property
    def extension(self) -> Optional[str]: ...
    @property
    def italian_leading_zero(self) -> bool: ...
    @property
    def number_of_leading_zeros(self) -> int: ...
    @property
    def raw_input(self) -> Optional[str]: ...
    @property
    def country_code_source(self) -> int: ...
    @property
    def preferred_domestic_carrier_code(self) -> Optional[str]: ...
    
    @staticmethod
    def from_phone_number(phone_number: PhoneNumber) -> FrozenPhoneNumber: ...
    def to_phone_number(self) -> PhoneNumber: ...
    
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class NumberFormat:
    @property
    def pattern(self) -> str: ...
    @pattern.setter
    def pattern(self, value: str) -> None: ...
    
    @property
    def format(self) -> str: ...
    @format.setter
    def format(self, value: str) -> None: ...
    
    @property
    def leading_digits_patterns(self) -> List[str]: ...
    @property
    def national_prefix_formatting_rule(self) -> str: ...
    @national_prefix_formatting_rule.setter
    def national_prefix_formatting_rule(self, value: str) -> None: ...
    
    @property
    def domestic_carrier_code_formatting_rule(self) -> str: ...
    @domestic_carrier_code_formatting_rule.setter
    def domestic_carrier_code_formatting_rule(self, value: str) -> None: ...
    
    @property
    def national_prefix_optional_when_formatting(self) -> bool: ...
    @national_prefix_optional_when_formatting.setter
    def national_prefix_optional_when_formatting(self, value: bool) -> None: ...
    
    def add_leading_digits_pattern(self, pattern: str) -> None: ...

class PhoneNumberDesc:
    @property
    def national_number_pattern(self) -> str: ...
    @national_number_pattern.setter
    def national_number_pattern(self, value: str) -> None: ...
    
    @property
    def example_number(self) -> str: ...
    @example_number.setter
    def example_number(self, value: str) -> None: ...
    
    @property
    def possible_lengths(self) -> List[int]: ...
    @property
    def possible_lengths_local_only(self) -> List[int]: ...
    
    def add_possible_length(self, length: int) -> None: ...
    def add_possible_length_local_only(self, length: int) -> None: ...

class PhoneMetadata:
    def __init__(self, region_code: str) -> None: ...
    
    @property
    def region_code(self) -> str: ...
    @property
    def country_code(self) -> int: ...
    @property
    def supported_types(self) -> List[int]: ...
    
    def get_example_number(self, number_type: Optional[int] = None) -> Optional[PhoneNumber]: ...
    def get_example_number_string(
        self, 
        number_type: Optional[int] = None, 
        format_type: int = PhoneNumberFormat.NATIONAL
    ) -> Optional[str]: ...
    def is_valid_number_for_region(self, phone_number: PhoneNumber) -> bool: ...
    def get_number_type(self, phone_number: PhoneNumber) -> int: ...

class PhoneNumberMatch:
    def __init__(self, start: int, raw_string: str, number: PhoneNumber) -> None: ...
    
    @property
    def number(self) -> PhoneNumber: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def raw_string(self) -> str: ...

class PhoneNumberMatcher(Iterator[PhoneNumberMatch]):
    def __init__(
        self, 
        text: str, 
        region: str, 
        leniency: Optional[int] = None, 
        max_tries: int = 65536
    ) -> None: ...
    
    def has_next(self) -> bool: ...
    def next(self) -> PhoneNumberMatch: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> PhoneNumberMatch: ...

class PhoneNumberUtil:
    def parse(
        self, 
        number_to_parse: str, 
        default_region: Optional[str] = None, 
        keep_raw_input: bool = False
    ) -> PhoneNumber: ...
    
    def format(self, number: PhoneNumber, format_type: int) -> str: ...
    def format_in_original_format(self, number: PhoneNumber, region_calling_from: str) -> str: ...
    def format_out_of_country_calling_number(
        self, 
        number: PhoneNumber, 
        region_calling_from: str
    ) -> str: ...
    
    def is_valid_number(self, number: PhoneNumber) -> bool: ...
    def is_valid_number_for_region(self, number: PhoneNumber, region_code: str) -> bool: ...
    def is_possible_number(self, number: PhoneNumber) -> bool: ...
    def is_possible_number_with_reason(self, number: PhoneNumber) -> int: ...
    def is_possible_number_string(self, number_string: str, region_dialing_from: str) -> bool: ...
    
    def get_number_type(self, number: PhoneNumber) -> int: ...
    def get_region_code_for_number(self, number: PhoneNumber) -> Optional[str]: ...
    def get_example_number(self, region_code: str) -> Optional[PhoneNumber]: ...
    def get_example_number_for_type(self, region_code: str, number_type: int) -> Optional[PhoneNumber]: ...
    def get_supported_regions(self) -> List[str]: ...
    def get_supported_calling_codes(self) -> List[int]: ...
    def get_supported_types_for_region(self, region_code: str) -> List[int]: ...
    def get_country_code_for_region(self, region_code: str) -> int: ...
    def get_region_code_for_country_code(self, country_code: int) -> str: ...
    
    def is_number_match(
        self, 
        first_number: Union[PhoneNumber, str], 
        second_number: Union[PhoneNumber, str]
    ) -> int: ...
    def is_number_geographical(
        self, 
        number_or_type: Union[PhoneNumber, int], 
        country_calling_code: Optional[int] = None
    ) -> bool: ...

# Module-level convenience functions
def parse(
    number_string: str, 
    region: Optional[str] = None, 
    keep_raw_input: bool = False
) -> PhoneNumber: ...

def format_number(
    number: PhoneNumber, 
    format_type: int = PhoneNumberFormat.E164
) -> str: ...

def format_in_original_format(number: PhoneNumber, region_calling_from: str) -> str: ...
def format_out_of_country_calling_number(number: PhoneNumber, region_calling_from: str) -> str: ...
def is_valid_number(number: PhoneNumber) -> bool: ...
def is_possible_number(number: PhoneNumber) -> bool: ...
def number_type(number: PhoneNumber) -> int: ...
def get_example_number(region_code: str) -> Optional[PhoneNumber]: ...

def parse_frozen(number_string: str, region: Optional[str] = None) -> FrozenPhoneNumber: ...
def format_frozen_number(
    frozen_number: FrozenPhoneNumber, 
    format_type: int = PhoneNumberFormat.E164
) -> str: ...
def is_valid_frozen_number(frozen_number: FrozenPhoneNumber) -> bool: ...

def get_supported_regions() -> List[str]: ...
def get_supported_calling_codes() -> List[int]: ...
def get_supported_types_for_region(region_code: str) -> List[int]: ...
def get_metadata_for_region(region_code: str) -> Optional[PhoneMetadata]: ...
def country_code_for_region(region_code: str) -> int: ...
def region_code_for_country_code(country_code: int) -> str: ...
def region_code_for_number(number: PhoneNumber) -> Optional[str]: ...

def is_number_match(
    first_number: Union[PhoneNumber, str], 
    second_number: Union[PhoneNumber, str]
) -> int: ...
def is_number_geographical(
    number_or_type: Union[PhoneNumber, int], 
    country_calling_code: Optional[int] = None
) -> bool: ...

def find_numbers(
    text: str, 
    region: str, 
    leniency: Optional[int] = None, 
    max_tries: int = 65536
) -> Generator[PhoneNumberMatch, None, None]: ...

def find_phone_numbers_in_text(
    text: str, 
    region: str, 
    leniency: Optional[int] = None
) -> List[PhoneNumberMatch]: ...

def description_for_number(
    number: PhoneNumber, 
    language: str = "en", 
    region: Optional[str] = None
) -> str: ...

def description_for_valid_number(
    number: PhoneNumber, 
    language: str = "en", 
    region: Optional[str] = None
) -> str: ...

def country_name_for_number(number: PhoneNumber, language: str = "en") -> str: ...